language: java

jdk:
  - oraclejdk11

sudo: false

install:
    - mvn -N io.takari:maven:wrapper -Dmaven=3.5.4
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
    - vyacheslav.l@hexlet.io
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)

#install: true
#script: ./mvnw clean install
